### ISSUE TITLE
Cargo build aborted

### ISSUE THREAD

**Issue by MayarAlfares** [pps-lab/rofl-project-code#1]
error[E0599]: no function or associated item named `from_str` found for struct `proc_macro::Literal` in the current scope

**Comment by hiddely** [comment]
This may have something to do with the rust version you are using, as some of our dependencies rely on specific nightly versions. What rust version are you using? (Output of `rustc -V` and `cargo -V`)

**Comment by MayarAlfares** [comment]
Yes, this issue happens with nightly-2021-05-11.
rust version: 1.55.0

**Comment by hiddely** [comment]
For future reference, the project depends on specific versions of dependencies that have since been updated (but are incompatible due to use of specific nightly features. Installing the following dependency versions resolves the issue:
```
cargo update -p proc-macro2 --precise 1.0.28
cargo update -p packed_simd_2 --precise 0.3.4
```

This is also done by the benchmarking suite that sets up the servers, as shown [here (main.yml)](https://github.com/pps-lab/rofl-project-code/blob/master/ansible/roles/e2e-common/tasks/main.yml#L108)

**Comment by mayank0403** [comment]
Resurrecting this issue because the build is still failing after following all instructions.

Some info:
```
> rustc -V                                                               
rustc 1.54.0-nightly (79e50bf77 2021-05-10)

> cargo -V                                                                
cargo 1.54.0-nightly (e51522ab3 2021-05-07)
```

This step fails:
```
> cargo update -p proc-macro2 --precise 1.0.28                                
    Updating crates.io index
error: failed to select a version for the requirement `proc-macro2 = "^1.0.40"`
candidate versions found which didn't match: 1.0.28
location searched: crates.io index
required by package `quote v1.0.20`
    ... which is depended on by `tonic-build v0.4.2`
    ... which is depended on by `rofl_service v0.1.0
```

I can get past this step by changing the manifest, but then this issue crops up:
```
> cargo build
error: failed to download `hashbrown v0.12.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.1/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

Can you please help?
