### ISSUE TITLE
Cargo build failing

### ISSUE THREAD

**Issue by mayank0403** [pps-lab/rofl-project-code#2]
Resurrecting this issue because the build is still failing after following all instructions.

Some info:
```
> rustc -V                                                               
rustc 1.54.0-nightly (79e50bf77 2021-05-10)

> cargo -V                                                                
cargo 1.54.0-nightly (e51522ab3 2021-05-07)
```

This step fails:
```
> cargo update -p proc-macro2 --precise 1.0.28                                
    Updating crates.io index
error: failed to select a version for the requirement `proc-macro2 = "^1.0.40"`
candidate versions found which didn't match: 1.0.28
location searched: crates.io index
required by package `quote v1.0.20`
    ... which is depended on by `tonic-build v0.4.2`
    ... which is depended on by `rofl_service v0.1.0
```

I can get past this step by changing the manifest, but then this issue crops up:
```
> cargo build
error: failed to download `hashbrown v0.12.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.1/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

Can you please help?

Thanks a lot,
Mayank

**Comment by hiddely** [comment]
Hi Mayank,

Thanks for pointing this out. I have updated the project to use a more recent Rust version (nightly-2022-07-24) with corresponding dependencies. `cargo build` now works without issues, without having to manually set any dependencies to older versions.

I have done some limited regression tests for the new dependencies and everything seemed to be working fine, but let me know if something is not working, I am happy to help 🙂.

Cheers,
Hidde
